local config  = require("novibe.config")
local consult = require("novibe.consult")

describe("novibe.consult.get_seed", function()
  it("does not error when provider is claude", function()
    config.setup({ provider = "claude" })
    local ok, result = pcall(consult.get_seed)
    assert.is_true(ok, result)
    assert.is_string(result)
  end)

  it("does not error when provider is opencode", function()
    config.setup({ provider = "opencode" })
    local ok, result = pcall(consult.get_seed)
    assert.is_true(ok, result)
    assert.is_string(result)
  end)

  it("includes PLAN MODE section for claude provider", function()
    config.setup({ provider = "claude" })
    local seed = consult.get_seed()
    assert.truthy(seed:find("PLAN MODE", 1, true))
    assert.truthy(seed:find("EnterPlanMode", 1, true))
  end)

  it("omits PLAN MODE section for non-claude providers", function()
    config.setup({ provider = "opencode" })
    local seed = consult.get_seed()
    assert.falsy(seed:find("PLAN MODE", 1, true))
  end)

  it("always includes AGENT session header", function()
    config.setup({ provider = "claude" })
    assert.truthy(consult.get_seed():find("AGENT session", 1, true))
    config.setup({ provider = "gemini" })
    assert.truthy(consult.get_seed():find("AGENT session", 1, true))
  end)
end)
