local no_vibe = require("novibe.no_vibe")

local function write_file(path, content)
  vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
  vim.fn.writefile(vim.split(content, "\n", { plain = true }), path)
end

local function with_tmp_dir(setup, fn)
  local dir = vim.fn.tempname()
  vim.fn.mkdir(dir, "p")
  if setup then setup(dir) end
  local prev = vim.fn.getcwd()
  vim.cmd("cd " .. vim.fn.fnameescape(dir))
  local ok, err = pcall(fn, dir)
  vim.cmd("cd " .. vim.fn.fnameescape(prev))
  vim.fn.delete(dir, "rf")
  if not ok then error(err, 2) end
end

local function with_no_vibe(content, fn)
  with_tmp_dir(function(dir)
    if content then write_file(dir .. "/NO_VIBE.md", content) end
  end, fn)
end

describe("no_vibe.load — NO_VIBE.md section filtering", function()
  it("returns nil when no rule files exist", function()
    with_no_vibe(nil, function()
      assert.is_nil(no_vibe.load("foo.ts"))
    end)
  end)

  it("includes the 'always' section regardless of filename", function()
    with_no_vibe("## always\nalways rule\n", function()
      local result = no_vibe.load("anything.rb")
      assert.truthy(result)
      assert.truthy(result:find("always rule"))
    end)
  end)

  it("includes section matching current filename", function()
    with_no_vibe("## *.tsx\nreact rule\n", function()
      local result = no_vibe.load("Button.tsx")
      assert.truthy(result)
      assert.truthy(result:find("react rule"))
    end)
  end)

  it("excludes sections that don't match filename", function()
    with_no_vibe("## *.py\npython rule\n", function()
      assert.is_nil(no_vibe.load("Button.tsx"))
    end)
  end)

  it("'always' section appears before file-specific sections", function()
    with_no_vibe("## *.tsx\nreact rule\n\n## always\nalways rule\n", function()
      local result = no_vibe.load("Button.tsx")
      local always_pos = result:find("always rule")
      local react_pos  = result:find("react rule")
      assert.truthy(always_pos < react_pos)
    end)
  end)

  it("returns nil when file exists but no sections match", function()
    with_no_vibe("## *.py\npython rule\n", function()
      assert.is_nil(no_vibe.load("Button.tsx"))
    end)
  end)

  it("skips sections with empty bodies", function()
    with_no_vibe("## *.tsx\n\n## always\nalways rule\n", function()
      local result = no_vibe.load("Button.tsx")
      assert.truthy(result)
      assert.falsy(result:find("%.tsx"))
    end)
  end)

  it("walks up parent directories to find NO_VIBE.md", function()
    with_no_vibe("## always\nfound it\n", function(dir)
      local subdir = dir .. "/a/b/c"
      vim.fn.mkdir(subdir, "p")
      vim.cmd("cd " .. vim.fn.fnameescape(subdir))
      local result = no_vibe.load("foo.ts")
      assert.truthy(result)
      assert.truthy(result:find("found it"))
    end)
  end)
end)

describe("no_vibe.load — convention-*.md files", function()
  it("loads a single convention file from .no_vibe/", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/.no_vibe/convention-project.md", "## always\nproject rule\n")
    end, function()
      local result = no_vibe.load("foo.ts")
      assert.truthy(result)
      assert.truthy(result:find("project rule"))
    end)
  end)

  it("merges multiple convention-*.md files", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/.no_vibe/convention-style.md",   "## always\nstyle rule\n")
      write_file(dir .. "/.no_vibe/convention-react.md",   "## *.tsx\nreact rule\n")
    end, function()
      local result = no_vibe.load("Button.tsx")
      assert.truthy(result:find("style rule"))
      assert.truthy(result:find("react rule"))
    end)
  end)

  it("loads convention files in sorted alphabetical order", function()
    with_tmp_dir(function(dir)
      -- using *.ts (not always) so order matches file load order;
      -- always-sections are intentionally prepended to the result.
      write_file(dir .. "/.no_vibe/convention-zzz.md", "## *.ts\nzzz rule\n")
      write_file(dir .. "/.no_vibe/convention-aaa.md", "## *.ts\naaa rule\n")
    end, function()
      local result = no_vibe.load("foo.ts")
      local aaa_pos = result:find("aaa rule")
      local zzz_pos = result:find("zzz rule")
      assert.truthy(aaa_pos < zzz_pos)
    end)
  end)

  it("filters convention sections by current filename", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/.no_vibe/convention-project.md", "## *.py\npython rule\n## *.tsx\nreact rule\n")
    end, function()
      local result = no_vibe.load("Button.tsx")
      assert.truthy(result:find("react rule"))
      assert.falsy(result:find("python rule"))
    end)
  end)
end)

describe("no_vibe.load — learned-*.md files", function()
  it("loads learned-*.md from .no_vibe/", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/.no_vibe/learned-style.md", "## always\nlearned rule\n")
    end, function()
      local result = no_vibe.load("foo.ts")
      assert.truthy(result:find("learned rule"))
    end)
  end)

  it("merges multiple learned-*.md files in sorted order", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/.no_vibe/learned-zzz.md", "## *.ts\nzzz learned\n")
      write_file(dir .. "/.no_vibe/learned-aaa.md", "## *.ts\naaa learned\n")
    end, function()
      local result = no_vibe.load("foo.ts")
      local aaa_pos = result:find("aaa learned")
      local zzz_pos = result:find("zzz learned")
      assert.truthy(aaa_pos < zzz_pos)
    end)
  end)
end)

describe("no_vibe.load — load order across sources", function()
  it("loads NO_VIBE.md before convention-*.md before learned-*.md", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/NO_VIBE.md",                     "## *.ts\nfrom novibe\n")
      write_file(dir .. "/.no_vibe/convention-project.md", "## *.ts\nfrom convention\n")
      write_file(dir .. "/.no_vibe/learned-style.md",      "## *.ts\nfrom learned\n")
    end, function()
      local result = no_vibe.load("foo.ts")
      assert.truthy(result)
      local novibe_pos     = result:find("from novibe")
      local convention_pos = result:find("from convention")
      local learned_pos    = result:find("from learned")
      assert.truthy(novibe_pos)
      assert.truthy(convention_pos)
      assert.truthy(learned_pos)
      assert.truthy(novibe_pos < convention_pos)
      assert.truthy(convention_pos < learned_pos)
    end)
  end)

  it("works with only convention files (no NO_VIBE.md)", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/.no_vibe/convention-project.md", "## always\nrule\n")
    end, function()
      local result = no_vibe.load("foo.ts")
      assert.truthy(result:find("rule"))
    end)
  end)

  it("works with only learned files (no NO_VIBE.md, no conventions)", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/.no_vibe/learned-style.md", "## always\nrule\n")
    end, function()
      local result = no_vibe.load("foo.ts")
      assert.truthy(result:find("rule"))
    end)
  end)

  it("walks up parent dirs to find .no_vibe/ even without NO_VIBE.md", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/.no_vibe/convention-project.md", "## always\nfound\n")
    end, function(dir)
      local subdir = dir .. "/a/b"
      vim.fn.mkdir(subdir, "p")
      vim.cmd("cd " .. vim.fn.fnameescape(subdir))
      local result = no_vibe.load("foo.ts")
      assert.truthy(result:find("found"))
    end)
  end)
end)

describe("no_vibe.discover — knowledge base fields", function()
  it("returns maps, rules, decisions as separate fields", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/.no_vibe/convention-project.md", "## always\nrule\n")
      write_file(dir .. "/.no_vibe/map-auth.md",           "## always\nmap\n")
      write_file(dir .. "/.no_vibe/rule-db.md",            "## always\nrule\n")
      write_file(dir .. "/.no_vibe/decision-api.md",       "## always\ndecision\n")
    end, function(dir)
      local found = no_vibe.discover()
      assert.truthy(found)
      assert.equals(1, #found.maps)
      assert.equals(1, #found.rules)
      assert.equals(1, #found.decisions)
      assert.truthy(found.maps[1]:find("map%-auth"))
      assert.truthy(found.rules[1]:find("rule%-db"))
      assert.truthy(found.decisions[1]:find("decision%-api"))
    end)
  end)

  it("returns empty tables when no KB files exist", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/.no_vibe/convention-project.md", "## always\nrule\n")
    end, function()
      local found = no_vibe.discover()
      assert.truthy(found)
      assert.same({}, found.maps)
      assert.same({}, found.rules)
      assert.same({}, found.decisions)
    end)
  end)

  it("knowledge field still contains merged maps + rules + decisions", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/.no_vibe/map-auth.md",     "## always\nmap\n")
      write_file(dir .. "/.no_vibe/rule-db.md",      "## always\nrule\n")
      write_file(dir .. "/.no_vibe/decision-api.md", "## always\ndecision\n")
    end, function()
      local found = no_vibe.discover()
      assert.truthy(found)
      assert.equals(3, #found.knowledge)
    end)
  end)

  it("returns multiple files per category in sorted order", function()
    with_tmp_dir(function(dir)
      write_file(dir .. "/.no_vibe/map-zzz.md", "## always\nz\n")
      write_file(dir .. "/.no_vibe/map-aaa.md", "## always\na\n")
    end, function()
      local found = no_vibe.discover()
      assert.truthy(found)
      assert.equals(2, #found.maps)
      assert.truthy(found.maps[1]:find("map%-aaa"))
      assert.truthy(found.maps[2]:find("map%-zzz"))
    end)
  end)
end)
